### ISSUE TITLE
avoid mktemp

### ISSUE THREAD

**Issue by wookietreiber** [vcftools/vcftools#10]
During linking, I get this warning:

```
variant_file_output.o: In function `variant_file::output_interchromosomal_genotype_r2(parameters const&)':
variant_file_output.cpp:(.text+0x95e4): warning: the use of `mktemp' is dangerous, better use `mkstemp'
```

See the bugs section of [the mktemp man page](http://linux.die.net/man/3/mktemp) for a more detailed explanation on why `mktemp` should be avoided.

The fix should be straightforward: replace all occurrences of `mktemp` with `mkstemp`. They have different return types, though.

**Comment by auton1** [comment]
Yes, I've seen this. However, it's not a completely trivial change, as (from memory) we use the filename returned by `mktemp` to open and close temp files as needed. This is necessary to avoid system limits on the number of temp files. However, `mkstmp` returns a file ID which would be lost when the file is closed.

**Comment by auton1** [comment]
Ahh. I see. This isn't actually as hard as I thought. We can use `mkstemp` to generate temp filenames after all. Here's a toy example I put together.
```
#include <iostream>
#include <fstream>
using namespace std;

int main(int argc, const char * argv[])
{
    // Create temp file name.
    char tmpname[] = "tmp.XXXXXX";
    mkstemp(tmpname);
    string saved_tmpname(tmpname);
    cout << "Temp Filename: " << saved_tmpname << endl;
    
    // Output a line to the temp file, and close the file.
    ofstream tmp_file1(saved_tmpname.c_str());
    tmp_file1 << "Test line 1" << endl;
    tmp_file1.close();
    
    // Reopen the other file, and append another line.
    ofstream tmp_file2(saved_tmpname.c_str(), ofstream::app);
    tmp_file2 << "Test line 2" << endl;
    tmp_file2.close();
    
    // Read the file, to check it worked.
    ifstream tmp_file_in(saved_tmpname.c_str());
    string line;
    while (getline(tmp_file_in, line))
        cout << line << endl;
    tmp_file_in.close();
    
    // Remove the temp file.
    remove(saved_tmpname.c_str());
    
    return 0;
}
```

So, this shouldn't be too hard a change after all. We'll see if we can find time to do it.

**Comment by wookietreiber** [comment]
I have two additional comments to your previous example:

1.  You need to close the file descriptor returned by `mkstemp` because it is already opened.

2.  (nitpicking) You do not need the `string saved_tmpname(tmpname);` because you are using only `c_str()` on it anyway which just returns `tmpname`.

The modified example looks like this:

```c
#include <stdlib.h>
#include <unistd.h>

#include <iostream>
#include <fstream>

using namespace std;

int main() {
  char tmp_file[] = "tmp.XXXXXX";
  int fd = mkstemp(tmp_file);
  close(fd); // close the created file descriptor

  cout << "Temp Filename: " << tmp_file << endl;

  // write a line to tmp_file
  ofstream tmp_stream1(tmp_file);
  tmp_stream1 << "Test line 1" << endl;
  tmp_stream1.close();

  // write another line to tmp_file
  ofstream tmp_stream2(tmp_file, ofstream::app);
  tmp_stream2 << "Test line 2" << endl;
  tmp_stream2.close();

  // read tmp_file to check it worked
  ifstream tmp_file_in(tmp_file);
  string line;
  while (getline(tmp_file_in, line))
    cout << line << endl;
  tmp_file_in.close();

  // remove tmp_file
  remove(tmp_file);
}
```

**Comment by wookietreiber** [comment]
Ah, I see you already implemented this. Great.
