### ISSUE TITLE
configure - zlib error

### ISSUE THREAD

**Issue by blueagave** [vcftools/vcftools#100]
Hello.  I'm attempting to build the vcftools master on a RHEL7 linux host, but running into the configure error below.  What do you suggest to resolve this?

$ ./autogen.sh
configure.ac:16: installing './compile'
configure.ac:12: installing './install-sh'
configure.ac:12: installing './missing'
src/cpp/Makefile.am: installing './depcomp'

$ ./configure
./configure: line 4636: syntax error near unexpected token `ZLIB,'
./configure: line 4636: `PKG_CHECK_MODULES(ZLIB, zlib)'

$ pkg-config --version
0.27.1

$ pkg-config --list-all | grep zlib
zlib                  zlib - zlib compression library

Thanks,
Tom

**Comment by rosset** [comment]
weird, it's working on centos7, install zlib-devel and try again.

yum install zlib-devel -y
git clone https://github.com/vcftools/vcftools.git
cd vcftools
sh autogen.sh
./configure
make

**Comment by rosset** [comment]
if you need 0.1.15 it's available on EPEL
https://koji.fedoraproject.org/koji/buildinfo?buildID=882121

**Comment by blueagave** [comment]
zlib-devel is already installed.  I'm actually, trying to install a vcftools fork at https://github.com/vcftools/vcftools/pull/69.  However, both the master and the fork produce the same configure error.

Name        : zlib-devel
Arch        : x86_64
Version     : 1.2.7
Release     : 15.el7

Name        : zlib
Arch        : x86_64
Version     : 1.2.7
Release     : 15.el7

**Comment by mmokrejs** [comment]
Inspect the real cause in confiig.log. You have to scroll a few pages back from the very end of the file.

**Comment by blueagave** [comment]
Thanks!  Using autoconf-2.69 and automake-1.13.4 (instead of automake-1-15) worked.

**Comment by rosset** [comment]
great, thanks, but current EL7 automake is automake-1.13.4-3.el7.noarch, why are you using automake-1.15? Also in Fedora I'm able to compile with these packages, so I'm not sure what happened in your RHEL environment.

rpm -q autoconf automake
autoconf-2.69-25.fc27.noarch
automake-1.15.1-2.fc27.noarch

**Comment by raonyguimaraes** [comment]
This is what fixed for me on ubuntu 16.04

sudo apt install gcc make autoconf automake pkg-config zlib1g-dev curl

**Comment by Leoan68** [comment]
> Thanks! Using autoconf-2.69 and automake-1.13.4 (instead of automake-1.15) worked.

I have met the same question with you, it was solved when I transfer the version from 1.15 to 1.13.4. Thanks!
