### ISSUE TITLE
4.2 downgrade to 4.1 something wrong

### ISSUE THREAD

**Issue by twelvesummer** [vcftools/vcftools#110]
4.1 vcf format：
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
4.2 vcf format 
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">

**Comment by auton1** [comment]
Unclear issue description
