### ISSUE TITLE
simple vcf output should work

### ISSUE THREAD

**Issue by golharam** [vcftools/vcftools#113]
This very simple command should generate a VCF file, but instead no output is generated.   I would expect the sites in the VCF file intersecting with the regions in the BED file, all the while, keeping the VCF header.   Using --stdout, --out had no effect.  --recode changed the output.  I just want to do a simple VCF intersect.

$ vcftools --vcf SL235666.vcf --bed hg38.mysites.bed         

VCFtools - 0.1.15
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--vcf SL235666.vcf
	--bed hg38.mysites.bed

After filtering, kept 1 out of 1 Individuals
	Read 84550 BED file entries.
After filtering, kept 2157 out of a possible 16156 Sites
Run Time = 2.00 seconds

**Comment by auton1** [comment]
You need the --recode and --out options.
