### ISSUE TITLE
vcftools exits successfully even when it fails

### ISSUE THREAD

**Issue by chapplec** [vcftools/vcftools#114]
When using version 0.1.15, `vcftools` exits with a 0 exit status even when an error such as a wrong command line switch or an nonexistent file occurred:

```
$  vcftools --vcf nonExistentFile && echo WORKED

VCFtools - UNKNOWN
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
        --vcf nonExistentFile

stat error: No such file or directory
Error: Can't determine file type of nonExistentFile
WORKED

$ vcftools --asdasdvcf nonExistentFile && echo WORKED

Error: Unknown option: --asdasdvcf

WORKED

```

This causes issues when `vcftools` is used as part of a pipeline which is supposed to fail if any of its components fails.

**Comment by auton1** [comment]
A fix has been checked into the main branch.
