### ISSUE TITLE
The command example on the vcftools.github.io 

### ISSUE THREAD

**Issue by tyto0314** [vcftools/vcftools#117]
In the example page

the example shows how to remove filtered variants should be

`vcftools --gzvcf input_file.vcf.gz --remove-filtered-all --recode --stdout | bgzip -c > output_PASS_only.vcf.gz`

instead of 

`vcftools --gzvcf input_file.vcf.gz --remove-filtered-all --recode --stdout | gzip -c > output_PASS_only.vcf.gz`

because I can't make index with tabix from the output below

**Comment by auton1** [comment]
Fixed.
