### ISSUE TITLE
vcf-consensus: for unphased heterozygous sites, always reports haplotype 1 as REF variant and H2 as ALT

### ISSUE THREAD

**Issue by elmoremh** [vcftools/vcftools#133]
It biases the output sequences, which I'm hoping to use for phylogenetics and diversity analyses. I know they won't be perfect under any circumstances (phasing was very imperfect), but I can't have them systematically biased so that one allele in each individual is always much closer to the reference genome. 

I'd suggest the script put in an N (or possibly the correct ambiguity code, though people often don't want those inserted in their data) at all unphased heterozygous sites, or at least give the user that option. 

(Btw, I really appreciate this script tackling alternate references for diploids at all!)

src/perl/vcf-consensus

**Comment by pd3** [comment]
Hi, this script is not supported anymore. Please check `bcftools consensus` instead. http://samtools.github.io/bcftools/bcftools.html#consensus

**Comment by elmoremh** [comment]
Sweet! Thank you so much! I was about to waste a week or two hacking my way
around this using the deprecated script.
