### ISSUE TITLE
./configure.ac: line 8: syntax error near unexpected token `[2.63]' ./configure.ac: line 8: `AC_PREREQ([2.63])'

### ISSUE THREAD

**Issue by eravallirao** [vcftools/vcftools#138]
Can anyone help me, I am getting this error while trying to run ./configure.ac file. I was asked to run ./configure file but that is not available in the asked folder rather ./configure.ac file is available

**Comment by eravallirao** [comment]
Sorry I found the solution. Ran the ./autogen.sh and it generated .configure file

**Comment by MuhammadMuneeb007** [comment]
./autogen.sh: 3: autoreconf: not found

sudo apt-get install autoconf automake pkg-config libgtk-3-dev

**Comment by QBanh** [comment]
> 
Hi, I have the same problem. Can you please send me the code for generating the configure file? Thanks.
