### ISSUE TITLE
convert vcf file from v4.1 to v4.2

### ISSUE THREAD

**Issue by GinaRe** [vcftools/vcftools#143]
Hello,

I would like to know if it's possible to convert a vcf file from v4.1 to v4.2 using vcftools. As I understand, vcf-convert only does conversion from VCFv3.3 to VCFv4.0. Is this correct?

**Comment by pd3** [comment]
If I remember correctly, it should be able to convert from v4.1 to v4.2 and also the usage page suggests so https://github.com/vcftools/vcftools/blob/master/src/perl/vcf-convert#L30
