### ISSUE TITLE
tab-delimited text file to VCF format conversion

### ISSUE THREAD

**Issue by s-usr** [vcftools/vcftools#144]
# Convert from VCF format to tab-delimited text file
> zcat file.vcf.gz | vcf-to-tab > out.tab 

It will be nice to have tab-delimited text file to VCF format conversion. Thanks.

**Comment by pd3** [comment]
Check `bcftools query` http://samtools.github.io/bcftools/bcftools.html#query

**Comment by s-usr** [comment]
Thanks. This assumes that one knows the format for a vcf file; in this case
> '%CHROM\t%POS\t%ID\t%REF\t%ALT\t%QUAL\t%FILTER\t%INFO\t%FORMAT\t%GT\n'

Do you know of a tested tool that converts a dna raw-data text file to VCF?

**Comment by s-usr** [comment]
From issue https://github.com/samtools/bcftools/issues/933
* Make CHROM identifiers in the 23andme file and the ref.fa file the same | Remove "chr" from the ref.fa file.

> bcftools convert -c ID,CHROM,POS,AA --tsv2vcf 23andme.txt --fasta-ref GRCh37.23andme.fa -s mySample -Oz -o mySample.vcf.gz

**Comment by s-usr** [comment]
If anyone has a link to the file 'GRCh37.23andme.fa', please share! Thanks.

**Comment by s-usr** [comment]
I opened an issue at #1076.
