### ISSUE TITLE
make error on macosx 10.15.2

### ISSUE THREAD

**Issue by eskamoah** [vcftools/vcftools#149]
(base) Noahs-MacBook-Pro-2:vcftools noah$ make
make  all-recursive
make[1]: Entering directory '/Users/noah/vcftools'
Making all in src
make[2]: Entering directory '/Users/noah/vcftools/src'
Making all in cpp
make[3]: Entering directory '/Users/noah/vcftools/src/cpp'
clang -DHAVE_CONFIG_H -I. -I../..   -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -MT vcftools-entry.o -MD -MP -MF .deps/vcftools-entry.Tpo -c -o vcftools-entry.o `test -f 'entry.cpp' || echo './'`entry.cpp
entry.cpp:32:34: error: use of undeclared identifier 'rpl_malloc'
        double * het_probs = (double *) malloc((size_t) (rare_copies + 1) * sizeof(double));
                                        ^
../../config.h:170:16: note: expanded from macro 'malloc'
#define malloc rpl_malloc
               ^
1 error generated.
make[3]: *** [Makefile:616: vcftools-entry.o] Error 1
make[3]: Leaving directory '/Users/noah/vcftools/src/cpp'
make[2]: *** [Makefile:319: all-recursive] Error 1
make[2]: Leaving directory '/Users/noah/vcftools/src'
make[1]: *** [Makefile:362: all-recursive] Error 1
make[1]: Leaving directory '/Users/noah/vcftools'
make: *** [Makefile:303: all] Error 2
(base) Noahs-MacBook-Pro-2:vcftools noah$

**Comment by eskamoah** [comment]
I had an error where it couldn't find "stdio.h", so I used this command

sudo ln -sf /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/ /Users/eskamoah/anaconda2/bin/../include/c++/

**Comment by shangyf-stu** [comment]
Hi, eskamoah
I have met the same error. Do you solve this problem?
Any suggestions are appreciated！

**Comment by victorlin** [comment]
While running Linux on `amd64` and cross-compiling for `arm64`, I noticed that this happens if emulation is not set up. Setting up emulation using [tonistiigi/binfmt](https://github.com/tonistiigi/binfmt) fixes it.

**Comment by victorlin** [comment]
Actually, even with emulation set up, this is still an issue. A workaround is to comment out `AC_FUNC_MALLOC` and `AC_FUNC_REALLOC` [as suggested on StackOverflow](https://stackoverflow.com/a/68541115/4410590) (https://github.com/victorlin/vcftools/commit/daaca64872d55e4c0d16abf39aab4096729add0e), though I don't know if that breaks anything.
