### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by Griffan** [vcftools/vcftools#16]
./configure: line 4634: syntax error near unexpected token `ZLIB,'

**Comment by auton1** [comment]
Can you be a bit more detailed with regard to the issue?

**Comment by wookietreiber** [comment]
Did you generate this configure script? If so, which autoconf version do you have? Would you please paste this exact version of the generated configure script to some pastebin, gist or other service?

**Comment by Griffan** [comment]
I use git clone to download code, then use the autogen.sh, then use configure --prefix=/my/install/dir. After a while, it stopped with this information prompt.

**Comment by wookietreiber** [comment]
Ok, I see where the problem is: The `pkg-config` check has not been translated from your `configure.ac` to `configure`, it has just been copied. I suppose that is because you either don't have `pkg-config` installed or it is installed incorrectly so that autoconf can not translate that line of the script.

You need to correctly install `pkg-config`.

The real problem here is, that the `autoconf` stage during `./autogen.sh` does not complain that there is no `pkg-config`. It just copies `PKG_CHECK_MODULES` lines instead of translating them.

**Comment by Griffan** [comment]
problem solved! Thanks!

**Comment by KhagayN** [comment]
i installed pkg-config use Homebrew but, the error still appears

**Comment by wookietreiber** [comment]
@KhagayN Would you please be more specific about your setup, command line and errors?

**Comment by cfblaeb** [comment]
Exact same error.
Ubuntu 14.04.
pkg-config installed with apt-get.
Autoconf 2.69.

cloned the github repo.
ran ./autogen.sh 
which outputted:
configure.ac:12: installing './install-sh'
configure.ac:12: installing './missing'
src/cpp/Makefile.am: installing './depcomp'

then ran ./configure --prefix=/mypath
which runs to line 4533 and exits with
checking how to run the C preprocessor... gcc -E
checking for perl... /usr/bin/perl
./configure: line 4533: syntax error near unexpected token `ZLIB,'
./configure: line 4533: `PKG_CHECK_MODULES(ZLIB, zlib)'

**Comment by edgarjavi** [comment]
do brew install pig-config
and then run ./autogen.sh again
and then ./configure
it worked for me

**Comment by clemgoub** [comment]
this worked well for me, using Mac OS 10.11.5
I needed to re-run ./autogen.sh as suggested.

Thanks a lot!

**Comment by zfisch** [comment]
in case it's helpful -- on ubuntu, installing pkg-config with linuxbrew failed for me. I had to `sudo apt-get pkg-config` and then rerun `./autogen.sh`.

**Comment by AnimaTardeb** [comment]
On El-Capitan I couldn't install pkg-config using pip.
I installed brew to install pkg-config and the thinks go quit good after 
Thanks for the help

**Comment by myheu** [comment]
For me, this dirdumvented the problem:
brew install homebrew/science/vcftools

**Comment by lab014** [comment]
I am working on OS X Yosemite (10.10.4) and `brew install pkg-config` solved my problem. Thanks!

**Comment by lldean18** [comment]
This solved my problem with install on Mac with M1 chip. Thank you!
