### ISSUE TITLE
man page not copied

### ISSUE THREAD

**Issue by ink1** [vcftools/vcftools#17]
Thank you for your continued efforts. Just a minor thing so apologies if it's already been fixed. The readme on the main page says to use configure but the release bundle still only has a makefile. The makefile is fine but it does not copy the man page. Everything is fine otherwise.

**Comment by auton1** [comment]
Yes, the 0.1.13 release still uses the makefile. The 0.1.14 release will use the new install procedure. However, we're holding off making the formal release in case any particularly worrying issues emerge during use 'in the wild'. I expect we'll move to the 0.1.14 release within the next couple of weeks.

**Comment by ink1** [comment]
OK, good to know.
Just tried building from git repo and it is nice of you to take care of zlib building options by providing ZLIB_CFLAGS and ZLIB_LIBS. I've been editing makefiles lately to replace the default zlib in order to improve performance. However with these two variables set to include path and lib path respectively everything worked just fine. Thanks!
