### ISSUE TITLE
Hudson Estimator for Fst

### ISSUE THREAD

**Issue by gideonite** [vcftools/vcftools#2]
Hello,

It's very convenient that vcftools has a built in Fst estimator from Weir and Cockerham's 1984 paper.

Unfortunately, for my work I am using the Hudson estimator described in [Bhatia et al, 2013](http://genome.cshlp.org/content/23/9/1514). I think that this estimator is also commonly used. Any chance vcftools could add the Hudson estimator? 

Thanks!

PS congratulations on moving to Github.

**Comment by auton1** [comment]
I'm afraid we're unlikely to implement this any time soon. However, if someone wanted to contribute the required code, we'd be happy to incorporate it.
