### ISSUE TITLE
Why is v0.1.14 tagged as pre-release?

### ISSUE THREAD

**Issue by wookietreiber** [vcftools/vcftools#20]
I would have expected either an ordinary release or the version being something like v.0.1.14rc1.

**Comment by amarcket** [comment]
At the moment I have set it as pre-release because I am trying to figure out an issue with the version tagging. For some reason, when you compile and run the binaries from the distribution created by github, the version number comes up as UNKNOWN.

**Comment by wookietreiber** [comment]
The reason for this UNKNOWN value is [this commit](https://github.com/vcftools/vcftools/commit/d3a688eefd672d70dcd644073410d181a4f82cd5). I don't know why the introduction of this `git-version-gen` script is neccessary, maybe @agordon can shed some light on this, who is the author of this commit.

I strongly believe, that whatever the reason was for introducing this change can be done with plain autoconf as well. Let me know if I can help. As I read it at the moment, the files `.version` and `.tarball-version` are created, but I don't know yet how and where they are used. Grep'ing for both of these files in current master, they are not used anywhere.

**Comment by agordon** [comment]
@amarcket - has 'UNKNOWN' been resolved (based on our emails?) if not let me know.

@wookietreiber - The `.tarball-version` is used in `configure.ac` as  parameter to `git-version-gen`, and is generated in `Makefile.am` when running `make dist`.
It is used to check the version *if* the user decides to do `./autogen.sh` from a tarball (instead of from a git repo), since 'git describe' will not work in such a case.
The `UNKNWON` version should be resolved (and it does seem resolved in the tarball available for download under the 'release' section).
I'm sure the script can be replaced with autoconf commands, but I would guess that if you want the same functionality of it, you'd end with with a similar script (or similar commands). The `git-version-gen` script is used in the same fashion in many other GNU packages, and so works quite well.

regards,
-gordon

**Comment by auton1** [comment]
Hmmm. Having just built vcftools from the github zip file, the current procedure leaves the label in the executable as UNKNOWN in the executable. This isn't ideal, as many users will install the program in this way. Advice welcome as to how to get this fixed, or changes required to the install procedure in the README.

**Comment by agordon** [comment]
I must say I was always confused by the "github zips" - they make no sense for compiled projects which use autotools. They give you the git repository snapshot without the git information,
but also without the necessary auto tools-generated files (which do exist in the 'tarball' that is generated by `make dist`).

A project which uses 'auto tools' should offer either git access to people who know how to do `git clone` (and then they are expected to have `automake` and `auto tools` installed on their computers), or download the official tarball (which `make dist` ensures requires nothing but shell, make, and a compiler).

This has always been the way autotools-based projects are distributed.
I don't get github's behavior in this case, but I guess I can't change the world.
(Downloading a copy of the git repository without the prepared files perhaps makes sense for other languages which don't require an intermediate step, but not autotools).

**Comment by wookietreiber** [comment]
I believe autotools is one of the very few build tools that has something like `make dist`, which does a bit more than just create a tarball, namely include all the autotools generated files. So, the GitHub-made release tarballs and zips are quite useful for projects that do not have a convenient way to generate a tarball by themselves. As far as I know, there is unfortunately no way to completely remove the GitHub-made release tarballs and zips for autotools projects.

I added both the [build from release tarball](https://github.com/vcftools/vcftools#build-from-release-tarball) and the [build from GitHub](https://github.com/vcftools/vcftools#build-from-github) sections to the README to provide instructions for both use cases. Also, there is `autogen.sh` to ease using autotools for end-users who want to build from a cloned repository.
