### ISSUE TITLE
issue on vcftools --max-missing option

### ISSUE THREAD

**Issue by bunop** [vcftools/vcftools#21]
Dear developers,

I saw a strange behavior using vcftools with `--max-missing` option: If I filter this [vcf](https://gist.githubusercontent.com/bunop/df06cd82c89b90d1704b/raw/3865a0c1317c9c879ef5356808c6b562292b8f93/input.vcf) file with `--minDP 2` and `--max-missing 0.7` in the same command line, I will retrieve SNPs called on 60% of my samples, while filtering before with `minDP` and then with `max-missing` on the intermediate file, I will get the correct number of SNPs. Those are my command lines (I've downloaded the current vcftools from github and I have exported it in my `$PATH` environment):

```bash
vcftools --vcf input.vcf --recode --recode-INFO-all --minDP 2 --max-missing 0.7 --out reference
vcftools --vcf input.vcf --recode --recode-INFO-all --minDP 2 --out tmp 
vcftools --vcf tmp.recode.vcf --recode --recode-INFO-all --max-missing 0.7 --out test
```

`reference.recode.vcf` has more SNPs than `test.recode.vcf` and the last seems to be correct. The VCF input file used for this test is available on my [gist](https://gist.github.com/bunop/df06cd82c89b90d1704b). Could be possible that the `minDP` option is not evaluated correctly by the `max-missing` option? Could be a problem on my input file? I was not able to reproduce this error on your vcf example files.

Thank you for your support,

regards,

Paolo

**Comment by auton1** [comment]
I think this is a filter precedence issue. By default, vcftools filters sites before genotypes. So, in the first command, the max-missing filter is applied first, and then the minDP filter is applied. In the second version, the minDP filter is being applied (masking out some genotypes), and then the max-missing filter is being applied. In this second version, the minDP filter can increase the per-site missingness, and hence the sites get subsequently filtered by the max-missing filter. 

Hope that makes sense.
