### ISSUE TITLE
Strange behavior in vcf-subset

### ISSUE THREAD

**Issue by mscampbell** [vcftools/vcftools#22]
I was using vcf-subset to split up a multi-vcf file and ran into a strange behavior. I've included one of the vcf lines that uncovered the behavior.

Before subset
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  15m     20_08   4212    49-11   56S     Egl210  Egl252  NPRW13-1
Contig0 376454  .       C       A,T     4175.23 .       AC=7,1;AF=0.438,0.063;AN=16;BaseQRankSum=-2.490;DP=298;Dels=0.00;FS=0.912;HaplotypeScore=0.2287;MLEAC=7,1;MLEAF=0.438,0.063;MQ=60.00;MQ0=0;MQRankSum=0.399;QD=21.09;ReadPosRankSum=0.425;SOR=0.661      GT:AD:APL:DP:GQ:PL      0/0:26,0,0:814,60,0,814,60,814,814,60,814,814:26:60:0,60,814,60,814,814 0/2:26,0,17:1600,630,552,1600,630,1600,970,0,970,918:43:99:552,630,1600,0,970,918       1/1:0,41,0:0,84,1173,84,1173,1173,84,1173,1173,1173:41:84:1173,84,0,1173,84,1173        0/0:34,0,0:1043,75,0,1043,75,1043,1043,75,1043,1043:34:75:0,75,1043,75,1043,1043        0/0:40,0,0:1637,120,0,1637,120,1637,1637,120,1637,1637:40:99:0,120,1637,120,1637,1637   1/1:0,42,0:0,102,1401,102,1401,1401,102,1401,1401,1401:42:99:1401,102,0,1401,102,1401   1/1:0,21,0:0,45,634,45,634,634,45,634,634,634:21:45:634,45,0,634,45,634 0/1:32,19,0:817,0,475,859,541,1401,859,541,1401,1401:51:99:475,0,817,541,859,1401

command: vcf-subset -c 20_08 mulit.vcf

After subset
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  20_08
Contig0 376454  .       C       T,A     4175.23 .       AC=1,0;AF=0.438,0.063;AN=2;BaseQRankSum=-2.490;DP=298;Dels=0.00;FS=0.912;HaplotypeScore=0.2287;MLEAC=7,1;MLEAF=0.438,0.063;MQ0=0;MQ=60.00;MQRankSum=0.399;QD=21.09;ReadPosRankSum=0.425;SOR=0.661       GT:AD:APL:DP:GQ:PL      0/1:26,0,17:1600,630,552,1600,630,1600,970,0,970,918:43:99:552,630,1600,0,970,918

The genotype was changed from 0/2 to 0/1 while everything else stayed the same. This came to our attention when we started looking at allele depths and found that the allele depth for one of the alleles in this individual was 0.

This was recapitulated using a git clone from today.

**Comment by bunop** [comment]
Dear mscampbell,

It seems that vcf-subset has inverted the `ALT` field, which was `A,T` and now is `T,A`, so genotype changed from `0/2` to `0/1` in order to have `C` as `REF` and `T` as ALT in both cases. In your example, it seems to be correct. Can you inspect the consistency of the others SNPs in your output file?

Regards,

Paolo

**Comment by mscampbell** [comment]
I see that the genotypes are correct but the the allele frequency information was not inverted with the alt field. In order for the inversion that vcftools did to be complete it should be 0/1:26,17,0. Sorry it took me so long to get back to you on this. The original email was in my spam for some reason and I didn't see this message util the notice the ticket was closed came it.
