### ISSUE TITLE
Syntax error while executing configure file.

### ISSUE THREAD

**Issue by bassdeveloper** [vcftools/vcftools#25]
$ ./configure.ac
./configure.ac: line 4: syntax error near unexpected token `[2.63]'
./configure.ac: line 4: `AC_PREREQ([2.63])'

# ./configure.ac
./configure.ac: 4: ./configure.ac: Syntax error: word unexpected (expecting ")")

**Comment by wookietreiber** [comment]
@bassdeveloper You are not supposed to execute `configure.ac` but `configure`. `configure.ac` is used by autoconf to generate `configure`.

Please follow the [build instructions](https://github.com/vcftools/vcftools#building-vcftools).

**Comment by bassdeveloper** [comment]
@wookietreiber  Thank you. My bad, autoconf was not installed! Sorry for raising this issue.
