### ISSUE TITLE
vcf-merge: column name prefix missing for first sample's column if all are similar

### ISSUE THREAD

**Issue by setempler** [vcftools/vcftools#27]
Hi,

vcf-merge creates custom column names (see [this line](https://github.com/vcftools/vcftools/blob/master/src/perl/vcf-merge#L235)).
However, if all vcf files contain the same column name, only from the second on the `col_prefix` is prepended. 

It would be nice to check if all column names are similar, and then also prepend the prefix to the first file's column.

Many thanks,
Sven

**Comment by gotero** [comment]
Have the same problem and request for enhancement.

**Comment by pd3** [comment]
Hi, vcf-merge is not actively developed any more, please use `bcftools merge` instead.

**Comment by setempler** [comment]
@pd3 thank you for the hint, will try your suggestion and open a new issue if necessary.

**Comment by gotero** [comment]
@pd3. Thanks for quick reply.
