### ISSUE TITLE
VCF validator with GRCh38

### ISSUE THREAD

**Issue by hmkim** [vcftools/vcftools#30]
$ perl -I vcftools/0.1.14/Library/Perl/5.18/ vcftools/0.1.14/bin/vcf-validator in.vcf
Colons not allowed in chromosome names: HLA-DRB1*16:02:01

Using GRCh38 reference genome, contig name is HLA-DRB1*16:02:01.

so, please check this issue.

**Comment by auton1** [comment]
Unfortunately, this is specifically forbidden in the VCF 4.2 spec:

> The colon symbol (:) must be absent from all chromosome names to avoid parsing errors when dealing with breakends.

[http://samtools.github.io/hts-specs/VCFv4.2.pdf](http://samtools.github.io/hts-specs/VCFv4.2.pdf)

As such, the validator is correct, and changing this would require a change to the VCF format.
