### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by rgarcia-herrera** [vcftools/vcftools#32]
I tried to filter the attached VCF using the attached BED file.

vcftools will use up all available memory, eventually freezing the computer.

Considering the VCF and BED file are small and my computer has almos 400Gb RAM I think it's a bug.

I'm running 0.1.14.
    $ vcftools --version
    VCFtools (0.1.14)

[Channelopathies_Manifest_ABC.txt](https://github.com/vcftools/vcftools/files/132951/Channelopathies_Manifest_ABC.txt)

[B01.PTL_HLPLX.vcf.gz](https://github.com/vcftools/vcftools/files/132952/B01.PTL_HLPLX.vcf.gz)

**Comment by auton1** [comment]
This appears to be an invalid BED file. The required columns should be chromosome, start position, and end position. This bed file has additional columns that aren't supported.
