### ISSUE TITLE
ZLIB_VERNUM definition

### ISSUE THREAD

**Issue by ink1** [vcftools/vcftools#37]
Hi! Sorry to bother you again about non-standard zlib integration. I really thought the issue is closed. A user reported the following message
```
Using zlib version: 1.2.3
Versions of zlib >= 1.2.4 will be *much* faster when reading zipped VCF files.
```
for a binary statically linked against 1.2.8. I was tempted to ignore this clearly incorrect error but then decided to look at the code. Unfortunately src/cpp/vcf_file.cpp and src/cpp/bcf_file.cpp behave differently if ZLIB_VERNUM is incorrectly detected (gzbuffer is not used) which may indeed lead to suboptimal performance even if a higher version of zlib is actually used. I guess this is because I'm using a non-standard zlib. It is easy to fix the problem by removing some lines in the code but I thought it is worth highlighting this and perhaps I am missing something more elegant and obvious.
This is on release 0.1.14
```
export ZLIB_CFLAGS="-I/apps/zlib/1.2.8/include"
export ZLIB_LIBS=/apps/zlib/1.2.8-cloudflare/lib/libz.a
./configure --prefix=/apps/vcftools/0.1.14
...
make
make install
```

Thanks

**Comment by ink1** [comment]
Ah! It comes from zlib.h but apparently ZLIB_CFLAGS is not being passed when vcf_file.cpp is compiled.

**Comment by wookietreiber** [comment]
I believe, you should be fine using this:

```
export CPPFLAGS="-I/apps/zlib/1.2.8/include"
export LDFLAGS="-L/apps/zlib/1.2.8-cloudflare/lib"
export LD_LIBRARY_PATH="/apps/zlib/1.2.8-cloudflare/lib:$LD_LIBRARY_PATH"
./configure --prefix=/apps/vcftools/0.1.14
```

Does that `-cloudflare` version of zlib not come with its own `lib/pkgconfig/zlib.pc`? If not, it's comparatively easy to write your own and set `export PKG_CONFIG_PATH=/apps/zlib/1.2.8-cloudflare/lib/pkgconfig`.

**Comment by ink1** [comment]
It does come with zlib.pc, it's based on the standard zlib after all. However I want to link it statically and therefore just setting PKG_CONFIG_PATH will not suffice. This is why I have to set at least ZLIB_LIBS. And I probably thought at the time that if I set ZLIB_CFLAGS I won't need to bother with PKG_CONFIG_PATH.
By the way, I run an overnight test on a large vcf.gz file (11GB) and the time to process it taken by the old build which throws "Using zlib version: 1.2.3" message and the one which does not is practically equal (both builds are linked against 1.2.8). Perhaps setting gzbuffer is not essential or depends on the underlying storage?
