### ISSUE TITLE
vcf-convert issue with fasta header files containing '|'

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [vcftools/vcftools#46]
The vcf-converter doesn't work with fasta reference files that contain a '|' in the header. It appears to call samtools faidx without quotation mark around the fasta header file.

Eg. cat variants.vcf| vcf-convert -r PST79_v4_1_pa_qcc22p_p.fasta -v 4.1 > variants_v41.vcf
sh: quiver: command not found
sh: pilon:423-1000423: command not found
[fai_fetch] Warning - Reference 000182F not found in FASTA file, returning empty sequence
Failed to fetch sequence in 000182F
The command "samtools faidx PST79_v4_1_pa_qcc22p_p.fasta 000182F|quiver|pilon:423-1000423" returned non-zero status 32512.
 at /anaconda/lib/perl5/site_perl/5.22.0/FaSlice.pm line 56.
    FaSlice::throw(FaSlice=HASH(0x101adde70), "The command \"samtools faidx PST79_v4_1_pa_qcc22p_p.fasta 0001"..., ".\x{a}") called at /anaconda/lib/perl5/site_perl/5.22.0/FaSlice.pm line 79
    FaSlice::cmd(FaSlice=HASH(0x101adde70), "samtools faidx PST79_v4_1_pa_qcc22p_p.fasta 000182F|quiver|pi"...) called at /anaconda/lib/perl5/site_perl/5.22.0/FaSlice.pm line 125
    FaSlice::read_chunk(FaSlice=HASH(0x101adde70), "000182F|quiver|pilon", 423) called at /anaconda/lib/perl5/site_perl/5.22.0/FaSlice.pm line 183
    FaSlice::get_slice(FaSlice=HASH(0x101adde70), "000182F|quiver|pilon", 423, 424) called at //anaconda/bin/vcf-convert line 150
    main::convert_file(HASH(0x100805480)) called at //anaconda/bin/vcf-convert line 12

Might be an easy fix to include 'header' when calling samtools faidx 'header'. otherwise "|"s are interpreted as piping.

**Comment by aavilaherrera** [comment]
I just ran into this as well. It is a few lines for a quick fix, but I am not sure if it covers all use cases or if it properly secures against unwanted commands being executed.
