### ISSUE TITLE
how to use the "ldhat" option for haploid genomes

### ISSUE THREAD

**Issue by roddypr** [vcftools/vcftools#49]
Hi,

I've tried using the vcftools --ldhat option for haploid genomes. This automatically created linesas if the genome I'm using was diploid:
>Sample1-0
11111101111111111101011100111111111111111111110000
1111000001000000000000001000000000001000010010
> Sample2-1
??????????????????????????????????????????????????
??????????????????????????????????????????????????

Is there an option to change this?

Roddy

**Comment by auton1** [comment]
I'm afraid there's no option to do this within VCFtools.
