### ISSUE TITLE
vctools 0.1.13 log file problem.

### ISSUE THREAD

**Issue by mortunco** [vcftools/vcftools#52]
Hi, I am having an issue related the creation of log file.

My aim is to parse log file to get overlapping mutations found in the vcf with my bed input. Therefore, i parse the log file.

I run this code in the HPC's clusters and headnode. During the process, If I run it with the head node it works just fine, created log files etc. But if I run in the cluster it somehow does not creates the log file.

What might be the cause of this problem ?

Best regards,

Tunc.

**Comment by auton1** [comment]
You could redirect (using '>' and '2>') the log files to a specific location.
