### ISSUE TITLE
syntax error during configure?

### ISSUE THREAD

**Issue by dantaki** [vcftools/vcftools#53]
I get a syntax error during configure? 

The OS I'm using is CentOS5

```
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for perl... /home/xxx/perl5/bin/perl
./configure: line 4634: syntax error near unexpected token `ZLIB,'
./configure: line 4634: `PKG_CHECK_MODULES(ZLIB, zlib)'
```

I downloaded pkg-config and it did not work. Rerunning the autogen.sh and configure produced the same error. If I comment out line 4634 and run make I get a bunch of undefined reference errors

I ensured pkg-config is available in my $PATH. Not sure why I can't install.

**Comment by wookietreiber** [comment]
I don't know how to get autoconf / pkg-config documentation for CentOS 5. Can you locally install the documentation via yum and check how the syntax is supposed to look like? That stuff is so old I don't know if it's even worth supporting it.

... damn 10 year support ... just ranting ...

**Comment by dantaki** [comment]
I do not have sudo privileges for yum on my server but the options for pkg-config is below

  -h, --help                              Show help options

Application Options:
  --version                               output version of pkg-config
  --modversion                            output version for package
  --atleast-pkgconfig-version=VERSION     require given version of pkg-config
  --libs                                  output all linker flags
  --static                                output linker flags for static linking
  --short-errors                          print short errors
  --libs-only-l                           output -l flags
  --libs-only-other                       output other libs (e.g. -pthread)
  --libs-only-L                           output -L flags
  --cflags                                output all pre-processor and compiler flags
  --cflags-only-I                         output -I flags
  --cflags-only-other                     output cflags not covered by the cflags-only-I option
  --variable=NAME                         get the value of variable named NAME
  --define-variable=NAME=VALUE            set variable NAME to VALUE
  --exists                                return 0 if the module(s) exist
  --print-variables                       output list of variables defined by the module
  --uninstalled                           return 0 if the uninstalled version of one or more module(s) or their dependencies will be used
  --atleast-version=VERSION               return 0 if the module is at least version VERSION
  --exact-version=VERSION                 return 0 if the module is at exactly version VERSION
  --max-version=VERSION                   return 0 if the module is at no newer than version VERSION
  --list-all                              list all known packages
  --debug                                 show verbose debug information
  --print-errors                          show verbose information about missing or conflicting packages (default unless --exists or --atleast/exact/max-version given on the command line)
  --silence-errors                        be silent about errors (default when --exists or --atleast/exact/max-version given on the command line)
  --errors-to-stdout                      print errors from --print-errors to stdout not stderr
  --print-provides                        print which packages the package provides
  --print-requires                        print which packages the package requires
  --print-requires-private                print which packages the package requires for static linking
  --validate                              validate a package's .pc file
  --define-prefix                         try to override the value of prefix for each .pc file found with a guesstimated value based on the location of the .pc file
  --dont-define-prefix                    don't try to override the value of prefix for each .pc file found with a guesstimated value based on the location of the .pc file
  --prefix-variable=PREFIX                set the name of the variable that pkg-config automatically sets

**Comment by hmontenegro** [comment]
I have the same issue on a SUSE Linux Enterprise Server 11 SP3, pkg-config version 0.23. 

Several (or at least some) clusters run on very old Red Hat / CentOS or SUSE, so in my opinion it is worth supporting it.

Is there anything I can do to help?

**Comment by wookietreiber** [comment]
Download the pkg-config / autoconf documentation for your old versions, figure out how it works, and provide a PR.

**Comment by hmontenegro** [comment]
Humm, the problem may be somewhere else, I installed a newer pkg-config (0.29.1) and got the same error. The problem may lie with the Perl or zlib installs. I will dig deeper and report when / if I have updates.

**Comment by wookietreiber** [comment]
@hmontenegro Did you also try re-running `autogen.sh` and then using the newly generated `configure`?

**Comment by hmontenegro** [comment]
Yes, I did re-run `autogen.sh`. Also tried removing the whole folder, cloning the repo again and getting a fresh start. Same error.

**Comment by m3t4Lm4n** [comment]
Same error on macOS Sierra. I've installed pkg-config and zlib with Homebrew but with same result.

`MacBook-Pro:vcftools miro$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for perl... /usr/bin/perl
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... no
configure: error: Package requirements (zlib) were not met:

No package 'zlib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ZLIB_CFLAGS
and ZLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
`

**Comment by wookietreiber** [comment]
@m3t4Lm4n That's not the same error as above! Your environment cannot *find* your zlib installation, while the original issue has syntax errors during `configure`.

As the output shows, check that your zlib installation is correctly shown by pkg-config, as in:

```
$ pkg-config --list-all | grep zlib
zlib                   zlib - zlib compression library
```

**Comment by Xiangmengkong** [comment]
I have exactly the same issue with @dantaki , with macOS Sierra. How did you solve the problem?

**Comment by amandahaponski** [comment]
I a similar error using macOS v10.9.5. Has anyone solved the error? Here's the output after I run the ./configure.

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for perl... /usr/bin/perl
./configure: line 4635: syntax error near unexpected token `ZLIB,'
./configure: line 4635: `PKG_CHECK_MODULES(ZLIB, zlib)'

**Comment by wookietreiber** [comment]
@amandahaponski: Does this command work for you?

```console
$ pkg-config --list-all | grep zlib
zlib                   zlib - zlib compression library
```

**Comment by amandahaponski** [comment]
@wookietreiber Thanks for the response. I tried that command and it gave an error. So I installed pkg-config and then redid the vcftools installation and it now appears to be working. Thanks again!!!!

**Comment by KIM7AZEN** [comment]
@hmontenegro  hey guy,  do you solve the problem?

**Comment by hmontenegro** [comment]
Yes, I did (today), thanks to some insistence and this post:

https://stackoverflow.com/questions/8578181/using-the-pkg-config-macro-pkg-check-modules-failing

Basically, I installed latest versions of m4, autoconf, automake, libtool and pkg-config all to the same folder, and set PATH accordingly. Then installed latest zlib and set PKG_CONFIG_PATH. Finally, running `./configure` worked.

**Comment by agladstein** [comment]
I had the same problem on Ubuntu 14_04
<img width="691" alt="screen shot 2017-08-17 at 10 37 52 am" src="https://user-images.githubusercontent.com/26617086/29426139-8b33b120-833a-11e7-90e4-87bab6941590.png">

I fixed it by installing pkg-config, then rerunning the ./autogen.sh
```
sudo apt-get update
sudo apt-get install pkg-config
./autogen.sh
./configure
make
sudo make install
```

**Comment by saurabhbelsare** [comment]
Hi, 
I'm running into the same problem. I tried all the steps @hmontenegro outlined in his final post, installing m4, autoconf, automake, libtool and pkg-config and installed zlib. However, I'm still getting this error. My OS, given by uname -a is

Linux 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Are there any other things that need to be fixed? What should the PKG_CONFIG_PATH variable be set to? I tried setting it to my directory where pkg-config was installed, but that didn't help either. 

Even with all of this, when I run ./configure, I still see this error:

./configure: line 4636: syntax error near unexpected token `ZLIB,'
./configure: line 4636: `PKG_CHECK_MODULES(ZLIB, zlib)'

Any other ideas? (This is a shared cluster, so I don't have sudo privileges)
Thanks.

**Comment by hmontenegro** [comment]
In my case, it was:

`export PKG_CONFIG_PATH=/home/hmontenegro/lib/zlib/zlib-1.2.8/lib/pkgconfig:$PKG_CONFIG_PATH`

after having installed zlib with:

`./configure --prefix=/home/hmontenegro/lib/zlib/zlib-1.2.8`

**Comment by saurabhbelsare** [comment]
I just tried that, and it's still giving me the same error. The only difference I can see is that I am using zlib 1.2.11 instead of 1.2.8. However, I was able to get vcftools to compile and on my local desktop relatively painlessly, even though I can't get it to compile on our cluster, so it might be something path/OS specific to the cluster. I'll try to figure it out with our cluster sysadmin. 
Thanks anyways!

**Comment by martin-mann** [comment]
Hi all,
we had a similar problem within our project when the `pkg.m4` macro was not installed properly along with `pkg-config` or `pkg-config` was even not installed at all.

I found a [solution here](http://gnu-automake.7480.n7.nabble.com/PKG-CHECK-MODULES-on-system-without-pkg-config-installed-td5295.html) that basically defined default macros of `PKG_*` to disable the configure syntax problems. Thus, adding the following to `configure.ac`

```[bash]
############  DEFAULT MACROS IF PKG-CONFIG MISSING ###############

# Check for pkg-config program, used for configuring some libraries.
#
m4_define_default([PKG_PROG_PKG_CONFIG],
	[AC_MSG_CHECKING([pkg-config])
		AC_MSG_RESULT([no])])

# run pkg-config check (otherwise done by first PKG_CHECK_MODULES call)
PKG_PROG_PKG_CONFIG 

# If the pkg-config autoconf support isn't installed, define its
# autoconf macro to disable any packages depending on it.
#
m4_define_default([PKG_CHECK_MODULES],
	[AC_MSG_CHECKING([$1])
	AC_MSG_RESULT([no])
	$4])
```

What you still miss with this is the check for your libraries of interest. For this you might want to setup simple compilation-checks as a fallback..

Hope that helps,
Martin

**Comment by GlyphDataServices** [comment]
`dnf update pkg-config` and `dnf install zlib-devel` , on Fedora Linux fixed this for me.

**Comment by student-t** [comment]
Re-running autogen.sh solved the problem.

**Comment by Timeroot** [comment]
At least on Ubuntu, note that having `zlib1g` installed does not satisfy. You need `zlib1g-devel`.
