### ISSUE TITLE
autogen.sh and configure error

### ISSUE THREAD

**Issue by dyollluap** [vcftools/vcftools#55]
Hi,

I tried installing from github following the README directions... I get an error for the configuration:

./autogen.sh: line 3: autoreconf: command not found

Using osx 10.11.6 , any suggestions?
Thanks

**Comment by wookietreiber** [comment]
You need to install the build essentials of your OS, including autoconf, automake, pkgconfig and a compiler.

**Comment by dyollluap** [comment]
I got this working on osx 10.11.6
1. Removed previous vcftools installation attempts
2. Installed: 
- autoconf
- pkg-config
- libtools
- automake
- zlib
Followed README (though tar download also requires ./autogen step)
