### ISSUE TITLE
How can I stop vcf-merge omitting duplicate snps ?

### ISSUE THREAD

**Issue by mortunco** [vcftools/vcftools#70]
Hi,

Thank you for developing this life saving suite.

I have multiple vcf files and I would like to merge it into a single super vcf. But the problem is during merge operation vcf-merge omits duplicates and introduce a SF label identifying which sample has that mutation. I always count the mutation numbers with row number therefore, SF tag in vcf-merge causes a problem.

```` bcftools merge``` directly omits it without reporting any additional tag like vcf-merge.

When I try ``` bcftools concat -a ``` the only problem is, the information that indicating which samples are written in that vcf ( aka sourceFile header in vcf-merge) is not presented. 

I know this is kinda very specific request but could you fix me if I am missing an obvious option that already does this. I am also okay with a solution that counts number of SNP in a vcf that also considers SF tag.

Best regards,

Tunc.

**Comment by pd3** [comment]
Hi, 
I don't understand what you exactly are you trying to do. I should start with saying that `vcf-merge` is not actively developed any more and has been replaced with `bcftools merge`. 

The `bcftools merge` and `concat` commands do something completely different. For example, if on output you have multiple files each with a single sample, `merge` creates a file with multiple samples while `concat` creates a file with a single sample.

**Comment by mortunco** [comment]
To be more clear,

1 ) I used vcf-merge to merge ~143 vcf files which belong to different patients to generate a single vcf that contains all of the mutations. It produced what I wanted expect it omitted duplicated snp in to a single one and label which patients have that snp with SF tag.

Here is the example of a two vcfs that merged with vcf-merge. Also, it has a vcf header (#SourceFile)  that tells which VCFs were merged.
```
VCF HEADER
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
15	69760310	.	C	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=0,1;VAF=0.1772;Variant_Classification=lincRNA;cosmic=COSN17010964;t_alt_count=14;t_ref_count=65
15	75819723	.	G	C	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=0;VAF=0.1507;Variant_Classification=Intron;cosmic=COSN17009695;t_alt_count=11;t_ref_count=62
9	128059305	.	T	A	.	.	Callers=broad,muse;NumCallers=2;SF=0;VAF=0.0471;Variant_Classification=Intron;t_alt_count=4;t_ref_count=81
1	24711203	.	A	T	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.1395;Variant_Classification=Intron;t_alt_count=6;t_ref_count=37
1	93340903	.	A	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.3077;Variant_Classification=Intron;cosmic=COSN16275454;t_alt_count=16;t_ref_count=36
11	10313317	.	C	T	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.449;Variant_Classification=Intron;cosmic=COSN16276266;repeat_masker=L1MC4;t_alt_count=22;t_ref_count=27
3	31297050	.	A	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.2182;Variant_Classification=IGR;cosmic=COSN16275850;repeat_masker=L2b;t_alt_count=12;t_ref_count=43
5	39905569	.	T	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.2917;Variant_Classification=IGR;cosmic=COSN16277634;t_alt_count=14;t_ref_count=34
5	73624179	.	A	T	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.3797;Variant_Classification=lincRNA;cosmic=COSN16275126;t_alt_count=30;t_ref_count=49
6	4321332	.	T	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;SF=1;VAF=0.3396;Variant_Classification=IGR;cosmic=COSN16276315;t_alt_count=18;t_ref_count=35
```
With bcftools concat -a, you can see that those mutations are written in different rows.

Please see mutation at chr 15 , 69760310
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
15	69760310	.	C	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.1772;cosmic=COSN17010964;t_alt_count=14;t_ref_count=65;Variant_Classification=lincRNA
15	69760310	.	C	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.0769;cosmic=COSN17010964;t_alt_count=5;t_ref_count=60;Variant_Classification=lincRNA
15	75819723	.	G	C	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.1507;cosmic=COSN17009695;t_alt_count=11;t_ref_count=62;Variant_Classification=Intron
9	128059305	.	T	A	.	.	Callers=broad,muse;NumCallers=2;VAF=0.0471;t_alt_count=4;t_ref_count=81;Variant_Classification=Intron
1	24711203	.	A	T	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.1395;t_alt_count=6;t_ref_count=37;Variant_Classification=Intron
1	93340903	.	A	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.3077;cosmic=COSN16275454;t_alt_count=16;t_ref_count=36;Variant_Classification=Intron
11	10313317	.	C	T	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.449;cosmic=COSN16276266;repeat_masker=L1MC4;t_alt_count=22;t_ref_count=27;Variant_Classification=Intron
3	31297050	.	A	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.2182;cosmic=COSN16275850;repeat_masker=L2b;t_alt_count=12;t_ref_count=43;Variant_Classification=IGR
5	39905569	.	T	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.2917;cosmic=COSN16277634;t_alt_count=14;t_ref_count=34;Variant_Classification=IGR
5	73624179	.	A	T	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.3797;cosmic=COSN16275126;t_alt_count=30;t_ref_count=49;Variant_Classification=lincRNA
6	4321332	.	T	G	.	.	Callers=broad,dkfz,muse,sanger;NumCallers=4;VAF=0.3396;cosmic=COSN16276315;t_alt_count=18;t_ref_count=35;Variant_Classification=IGR
```
What I actually want ```bcftools concat -a```  + ```vcftools ##sourceFiles_ ``` option.

Best,

Tunc.

**Comment by pd3** [comment]
We don't have a tool to do this directly, but it can be done in one extra step. Add a custom INFO annotation with different value to each input file, for example by a simple awk command. The concatenation step leaves the annotations unchanged, so the source information will be preserved.

The awk command could look something like this

    awk '{OFS="\t"}{if ($line~/^#/) print $line; else{$8=sprintf("%s;SRC=FILE1",$8);print $line} }'

A definition of the SRC tag would need to be added to the header as well.
