### ISSUE TITLE
Conversion to 012 matrix issue

### ISSUE THREAD

**Issue by clemgoub** [vcftools/vcftools#71]
Hello,

I encounter for the first time this issue while I am converting a multi-sample vcf genotype file into a 012 matrix. After conversion, I have more sites in the out.012.pos file (list of the outputed positions) than the number of actual columns in my out.012 file (1 column = 1 loci).
For the context, I am doing that on the 1000 genomes phase 3 data and this only occurs for the chr2. Out of 610202 loci, I only get 585727 in the matrix and 610202 in the position file.

Any ideas? I'm lost!

Thanks!

Clément

**Comment by auton1** [comment]
This function only outputs biallelic loci. Are the missing sites multiallelic?
