### ISSUE TITLE
Error in documentation for `--relatedness` or bug in code

### ISSUE THREAD

**Issue by sooheelee** [vcftools/vcftools#74]
Currently, documentation says `--relatedness` values to self should be 1:
![screenshot 2017-03-12 11 44 18](https://cloud.githubusercontent.com/assets/11543866/23833242/42d37746-0719-11e7-913f-64b0f228f60e.png)

However, when I run the `--relatedness` function, the values for `RELATEDNESS_AJK` to self are ~0.4. 

Values for `--relatedness2` are 0.5.

What's going on?

**Comment by auton1** [comment]
This is a statement about the "expected" behaviour of the statistic under ideal conditions. Real data may diverge from that expectation.

**Comment by sooheelee** [comment]
Alright. Thanks for the explanation.
