### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by tseemann** [vcftools/vcftools#75]
It would be great if you could make a new tagged release (30 commits since) so we can update the Brew and Conda packages.

Thanks!

**Comment by auton1** [comment]
Please see the pre-release v0.1.15 and let me know if this addresses your needs.

**Comment by datakid** [comment]
The 0.1.15 release contains a lot of ._* files that should be removed.

**Comment by tseemann** [comment]
@auton1 i think they are MacOS resource fork files?

**Comment by tseemann** [comment]
My brew colleagues updated the package.
