### ISSUE TITLE
VCF validator - Error: AD expects 3 not 2 

### ISSUE THREAD

**Issue by thomasyu888** [vcftools/vcftools#82]
The error message is 
```
column NORMAL at 2:217498305 .. FORMAT tag [AD] expected different number of values (expected 3, found 2)
```

however, the spec says:

```
We have the AD field, which is a vector of 2 values per sample.
```
Does the tool need to be updated or does the spec need to be updated?

**Comment by pd3** [comment]
This sentence only describes the example, for a definition look in the section describing genotype fields:

     AD, ADF, ADR: read depths for each allele; total (AD), on the forward (ADF) 
     and the reverse (ADR) strand  (Integer, Number=R)

**Comment by thomasyu888** [comment]
Thanks for the explanation!
