### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by thkuo** [vcftools/vcftools#89]
I just installed vcftools with github and the commands:
```
./configure --prefix=/home/my/bin --exec-prefix=/home/my/bin/vcftools/
make
make install
```
When I tested vcf-consensus, however, it shows
```
Can't locate Vcf.pm in @INC
```
The module actually can be found under ```/home/my/bin/vcftools/lib/perl5/site_perl/5.24.0```. How can I solve the problem?

**Comment by pd3** [comment]
Hi,

the PERL5LIB variable needs to be set, please see here
https://vcftools.github.io/examples.html

Petr


On Tue, 2017-11-07 at 10:12 +0000, Tzu-Hao Kuo wrote:
> I just installed vcftools with github and the commands:
> ./configure --prefix=/home/my/bin --exec-
> prefix=/home/my/bin/vcftools/
> make
> make install
> When I tested vcf-consensus, however, it shows
> Can't locate Vcf.pm in @INC
> The module actually can be found under
> /home/my/bin/vcftools/lib/perl5/site_perl/5.24.0. How can I solve the
> problem?
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by thkuo** [comment]
It works. Many thanks!
