### ISSUE TITLE
What did vcftools merge do when SF=filtered 

### ISSUE THREAD

**Issue by yeswzc** [vcftools/vcftools#93]
Hi,

As in the header of file merged by vcftools:
##INFO=<ID=SF,Number=.,Type=String,Description="Source File (index to sourceFiles, f when filtered)">

I saw some positon had SF with a f followed a digit numer.
What did vcftools do when a SF was f ?

**Comment by pd3** [comment]
It's doing exactly the same thing, only indicates that the site had a FILTER set in the source file.

By the way, I recommend moving from the old `vcf-merge` to `bcftools merge`. The former is much slower and is not supported anymore.

**Comment by yeswzc** [comment]
Thank you.
