### ISSUE TITLE
error: configure

### ISSUE THREAD

**Issue by kyuca00** [vcftools/vcftools#95]
I recently download the latest version of vcftools, and had an error as below: 

$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for perl... /usr/bin/perl
./configure: line 4636: syntax error near unexpected token `ZLIB,'
./configure: line 4636: `PKG_CHECK_MODULES(ZLIB, zlib)'

------
Please tell me how to solve this situation!
Yuka

**Comment by ramesh8v** [comment]
I'm also running into the same issue. Did you solve this?

**Comment by auton1** [comment]
You need zlib installed.

**Comment by Timeroot** [comment]
In case someone else gets here stuck like me, you don't just need zlib installed, you need zlib's development package. On Ubuntu, `sudo apt-get install zlib1g-dev` -- having just `zlib1g` will *not* work.
