### ISSUE TITLE
problem using chr chroms with fill-fs 

### ISSUE THREAD

**Issue by cgates** [vcftools/vcftools#98]
Hi.
Thanks for vcftools!
I ran into a problem using fill-fs where it would annotate the first variant correctly, but all the remaining variants were just Ns. I believe I traced it to line 105 in 

FaSlice.pm:cache_chr_lengths
{
  ...      
        # original line: my $chr = $$self{chr_naming}.$items[0];
        my $chr = $items[0];
...
}

FYI, the chromosome naming convention of my fasta and VCF is "chr1, chr2, etc" so $$self{chr_naming} evaluates to "chr".
The original line 105 above prepends "chr" to the fai chromosome to make a hash of chromosome lengths that looks like this:
'chrchr1' => '249250621',
'chrchr2' => '243199373',
etc.

This hash apparently confuses line 117 in FaSlice.pm:read_chunk where it see that the hash is defined, but can't find the size for the requested chrom (because of the wonky hash above), and so incorrectly resets the $$self{to} making all subsequent calls to get_slice out of bounds.

If I use the uncommented line above, fill-fs works swimmingly.
Does this make any sense? 

FWIW, I have installed perl-vcftools-vcf (0.953) via bioconda.
cg

**Comment by pd3** [comment]
Indeed, this looks like a bug. Thank you for tracing it down and reporting.
